// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
   "aws_project_region": "us-east-1",
   "aws_cognito_identity_pool_id": "us-east-1:24e7558c-ca0a-4d00-91d4-e7bcc2415ca8",
   "aws_cognito_region": "us-east-1",
   "aws_user_pools_id": "us-east-1_ugFqTTPz4",
   "aws_user_pools_web_client_id": "17itb4oer5qu7vd188dbajufcn",
   "aws_content_delivery_bucket": "mplifyestroject-20190108175733-hostingbucket",
   "aws_content_delivery_bucket_region": "us-east-1",
   "aws_content_delivery_url": "http://mplifyestroject-20190108175733-hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;