// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "iot-20190108121054-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://iot-20190108121054-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:d888698f-1107-4164-afdb-c53db5329982",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GhDvO3QDa",
    "aws_user_pools_web_client_id": "5eajl2f5beg4bh0t618fc9uba6",
    "aws_mobile_analytics_app_id": "3a697fbe7d1b4407926f86427296a9b1",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
